KabanShop/KabanShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls'))

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KabanShop/shop/urls.py
from django.urls import path
from .import views


app_name = 'shop'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('shop/', views.shop_view, name='products'),
    path('cart/', views.cart_view, name='cart'),
    path('shop/<slug:category_slug>/', views.category_view, name='category'),
    path('shop/<slug:category_slug>/<slug:product_slug>/', views.product_view, name='product'),
    path('shop/<slug:category_slug>/<slug:product_slug>/to_cart', views.order_view, name='order'),
    path('shop/<slug:category_slug>/<slug:product_slug>/to_cart/order_error', views.order_error_view,
         name='order_error'),
    path('shop/<slug:category_slug>/<slug:product_slug>/to_cart/ordered', views.added_to_cart_view,
         name='added_to_cart'),
    path('cart/delete_product/<int:product_id>', views.delete_product_view, name='delete_product'),
    path('cart/ordered/', views.ordered_view, name='ordered'),
    path('cart/fill_profile', views.fill_profile_view, name='fill_profile'),

]

KabanShop/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register_user, name='register'),
    path('log_out/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit_profile', views.edit_profile_view, name='edit_profile'),

]

KabanShop/shop/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
# Модель, отвечающая за распределение товаров по категориям
class Category(models.Model):
    title = models.CharField(max_length=250, verbose_name='Категория', null=True, blank=True)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    preview = models.ImageField(upload_to='media/category_photo', verbose_name='Фото-превью', null=True, blank=True)
    category_slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/shop/{self.category_slug}'

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


# Модель, отвечающая за карточку товара
class Product(models.Model):
    # Название товара
    title = models.CharField(max_length=300, verbose_name='Название', null=True, blank=True)
    # Описание
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    # Доступность товара в магазине
    availability = models.BooleanField(verbose_name='Доступен в магазине', null=True, blank=True)
    # Цена
    price = models.FloatField(verbose_name='Цена', null=True, blank=True)
    # Количество доступных единиц товара
    count = models.IntegerField(verbose_name='Количество доступных товаров', null=True, blank=True)
    # Привязываем товары к определенной категории(например бытовая техника, продукты и т.п.)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    # Слаг. Об этом читать в методичке
    product_slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/shop/{self.category.category_slug}/{self.product_slug}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id', 'title']


# Модель склада
class WareHouse(models.Model):
    # Если товар продается в магазине - значит он может потенциально быть на складе
    # Поэтому делаем связку с таблицей товаров
    # При удалении товара из магазина, т.е если он больше не продается - удаляем всю информацию о нем со склада
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    # Наличие товара на складе. True, если количество >0
    availability = models.BooleanField(verbose_name='Есть на складе')
    # Количество товара на складе
    count = models.IntegerField('Количество')

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Товар на склад'
        verbose_name_plural = 'Товары на складе'


# Модель фотографий товаров
'''
    Фотографии товаров вынесены в отдельную модель ввиду того, что в карточке 
    одного товара может быть несколько фотографий данного товара. 
    Это позволит нам добавлять неограниченное количество фото и просто связывать их с конкретным товаром 
    с использованием внешнего ключа. Таким образом при получении нужного товара 
    у нас будет возможность получить все связанные с ним фото. 
    При удалении товара - все фото, которые связаны с ним будут удалены
'''


class ProductPhoto(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    photo = models.ImageField(upload_to='media/product_photo', verbose_name='Фото товара', null=True, blank=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Фото товара'
        verbose_name_plural = 'Фото товара'


# Модель корзины
class Cart(models.Model):
    product = models.CharField(max_length=200, verbose_name='Товар', null=True, blank=True)
    price = models.FloatField(verbose_name='Цена', null=True, blank=True)
    count = models.IntegerField(verbose_name='Количество', null=True, blank=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Покупатель', null=True, blank=True)

    def __str__(self):
        return self.product

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары в корзине'


class RemovedCategories(models.Model):
    title = models.CharField(max_length=250, verbose_name='Категория', null=True, blank=True)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    preview = models.ImageField(upload_to='media/category_photo', verbose_name='Фото-превью', null=True, blank=True)
    category_slug = models.SlugField(max_length=250, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Удаленную категорию'
        verbose_name_plural = 'Удаленные категории'

KabanShop/shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Cart


class OrderForm(forms.ModelForm):
    count = forms.IntegerField(min_value=0, label='Количество')

    class Meta:
        model = Cart
        fields = ['count']

KabanShop/shop/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import OrderForm
from django.contrib.auth.decorators import login_required
from users.models import UserProfile


# Create your views here.
def index_view(request):
    return render(request, 'shop/index.html')


def shop_view(request):
    categories = Category.objects.order_by('title')

    context = {'categories': categories}
    return render(request, 'shop/shop.html', context=context)


@login_required(login_url='users:login')
def cart_view(request):
    products_in_cart = Cart.objects.filter(buyer_id=request.user)
    final_price = 0
    for product in products_in_cart:
        final_price += product.price * product.count
    context = {'products': products_in_cart, 'final_price':final_price}
    return render(request, 'shop/cart.html', context=context)


def category_view(request, category_slug):
    category = Category.objects.get(category_slug=category_slug)
    products = Product.objects.filter(category_id=category.id).order_by('title')

    context = {'category': category, 'products': products}

    return render(request, 'shop/category.html', context=context)


def product_view(request, category_slug, product_slug):
    # Получаем данные из БД с использованием фильтраций в селектах.
    category = Category.objects.get(category_slug=category_slug)
    product = Product.objects.get(product_slug=product_slug)
    product_photo = ProductPhoto.objects.prefetch_related('product').filter(product_id=product.id)

    # Формируем словарь, содержащий данные, которые будут переданы в ответе с сервера
    # при формировании страницы
    context = {'category': category, 'product': product, 'product_photo': product_photo}

    # Возвращаем ответ от сервера в виде шаблона, который отображает страницу и данных из БД
    return render(request, 'shop/product.html', context=context)


@login_required(login_url='users:login')
def order_error_view(request, category_slug, product_slug):
    category = Category.objects.get(category_slug=category_slug)
    product = Product.objects.get(product_slug=product_slug)

    context = {'category': category, 'product': product}

    return render(request, 'shop/order_error.html', context=context)


@login_required(login_url='users:login')
def added_to_cart_view(request, category_slug, product_slug):
    category = Category.objects.get(category_slug=category_slug)
    product = Product.objects.get(product_slug=product_slug)
    context = {'category': category, 'product': product}
    return render(request, 'shop/added_to_cart.html', context=context)


@login_required(login_url='users:login')
def order_view(request, category_slug, product_slug):
    product = Product.objects.get(product_slug=product_slug)

    error = False
    try:
        product_in_ware_house = WareHouse.objects.get(product_id=product.id)
    except WareHouse.DoesNotExist:
        error = True
    finally:
        if error:
            product_in_ware_house = None
        else:
            product_in_ware_house = WareHouse.objects.get(product_id = product.id)

    category = Category.objects.get(category_slug=category_slug)
    available_product_count = product.count
    if product_in_ware_house:
        available_product_count += product_in_ware_house.count

    if request.method != 'POST':
        form = OrderForm()
    else:
        form = OrderForm(data=request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.product = product.title
            new_order.price = product.price
            new_order.buyer = request.user
            if new_order.count > available_product_count:
                return redirect('shop:order_error', category.category_slug, product.product_slug)
            elif new_order.count < available_product_count:
                if new_order.count < product.count:
                    product.count -= new_order.count
                    product.save()
                elif product.count - new_order.count < 10:
                    product_in_ware_house = WareHouse.objects.get(product_id=product.id)
                    product.count = available_product_count - new_order.count
                    product_in_ware_house.count = 0
                    product_in_ware_house.availability = False
                    product.save()
                    product_in_ware_house.save()
            else:
                product_in_ware_house = WareHouse.objects.get(product_id=product.id)
                new_order.count = available_product_count
                product.delete()
                if product_in_ware_house:
                    product_in_ware_house.count = 0
                    product_in_ware_house.availability = False
                    product_in_ware_house.save()
            form.save()
            return redirect('shop:added_to_cart', category.category_slug, product.product_slug)
    context = {'category': category, 'product': product, 'form': form}
    return render(request, 'shop/order.html', context=context)


@login_required(login_url='users:login')
def delete_product_view(request, product_id):
    product = Cart.objects.get(id=product_id)
    product_in_shop = Product.objects.get(title=product.product)
    product_in_shop.count += product.count
    product_in_shop.save()
    product.delete()
    return redirect('shop:cart')


@login_required(login_url='users:login')
def fill_profile_view(request):
    return render(request, 'shop/fill_profile.html')


@login_required(login_url='users:login')
def ordered_view(request):
    user_profile = UserProfile.objects.get(email=request.user.email)
    if user_profile:
        if user_profile.email and user_profile.phone_number and user_profile.address:
            products = Cart.objects.filter(buyer_id=request.user)
            for product in products:
                product.delete()
            return render(request, 'shop/ordered.html')

    return redirect('shop:fill_profile')

KabanShop/shop/templates/shop/added_to_cart.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Товар в корзине{% endblock %}

{% block page_header %}
    <h1>Товар добавлен в корзине</h1>
{% endblock %}

{% block content %}
    <div class="added-to-cart-container">
        <h3>Товар успешно добавлен в корзину</h3>
        <a href="{% url 'shop:products' %}" class="btn btn-success">Продолжить покупки</a>
        <a href="{% url 'shop:cart' %}" class="btn btn-primary">Перейти к корзине</a>
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/added_to_cart_styles.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/base.html
{% load django_bootstrap5 %}
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'shop/css/base.css' %}">
    <link rel="icon" href="{% static 'shop/images/icon/icon.jpeg' %}">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'shop:index' %}" style="font-size: 20pt">
                <img src="{% static 'shop/images/logo/logo.png' %}" alt="logo" width="50px" height="50px" >
                Главная</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation" aria-controls="navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse" style="font-size: 14pt">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:products' %}">Каталог товаров</a>
                    </li>
                </ul>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:cart' %}">Корзина
                            <img src="{% static 'shop/images/cart/cart.png' %}" alt="cart"
                            width="25px" height="25px"></a>
                    </li>
                </ul>
                <ul class="navbar-nav mr-auto" style="font-size: 14pt">
                    {% if user.is_authenticated %}
                        <span class="navbar-text"><strong>Здравствуйте, {{ user.username }}!</strong></span>
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Управление</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                            </li>
                        {% else %}
                            {% if avatar %}
                                <li class="nav-item">
                                   <img src="{{avatar.url}}" alt="user_avatar" width="60px" style="border-radius: 20px; margin-left: 7px;">
                                </li>
                            {% else %}
                                <li class="nav-item">
                                   <img src="{% static 'shop/images/avatars/void_avatar.jpg' %}"
                                        alt="user_avatar" width="60px" style="border-radius: 20px; margin-left: 7px;">
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:profile' %}">Перейти в профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'users:register' %}" class="nav-link">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>

        </nav>

        <main role="main" class="container">
            <div class="base">
                <div class="header pb-2 mb-2 border-bottom">
                    {% block page_header %}{% endblock %}
                </div>
                <div class="content">
                    {% block content %}{% endblock %}
                </div>

                <div class="footer">
                    <div style="float: left; margin-right: 15px">
                        <h6>По возникающим вопросам писать на почту
                            <br>или в телеграм</h6>
                        <div>kabanshop53@gmail.com</div>
                        <div><a href="#" style="color: black">KabanShop</a></div>
                    </div>

                    <div style="float: left; margin-right: 15px">
                        <h6 style="text-align: left;  width: 135px">Чаты в соцсетях</h6>
                        <div style=" float: left; margin-right: 15px">
                            <a href="#" target="_blank"><img src="{% static 'shop/images/logo/img_1.png' %}" alt="" width="60px" height="60px"></a>
                        </div>

                        <div style="margin-top: 5px;">
                            <a href="#" target="_blank"><img src="{% static 'shop/images/logo/img_2.png' %}" alt="" width="60px" height="60px"></a>
                        </div>
                    </div>
                    <div style="float: left">
                        <h6>Сервер в Discord</h6>
                        <div style="margin-right: 15px; float: left">
                            <a href="#" target="_blank"><img src="{% static 'shop/images/logo/ds_logo.png' %}" alt="Discord" width="60px" height="60px"></a>
                        </div>
                    </div>
                </div>
            </div>
        </main>



        <div class="btn-up btn-up_hide"></div>
        <script src="{% static 'shop/js/base.js' %}"></script>
    </body>
</html>

KabanShop/shop/templates/shop/cart.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Корзина{% endblock %}

{% block page_header %}
    <h1>Корзина</h1>
{% endblock %}

{% block content %}
    <div class="cart-container">
        {% for product in products %}
            <div class="cart-item">
                <div class="item-details">
                    <h3>{{ product.product }}</h3>
                    <p>Количество: {{ product.count }}</p>
                    <p>Цена: {{ product.price }} руб.</p>
                </div>
                <a href="{% url 'shop:delete_product' product.id %}" class="btn btn-danger btn-sm delete-button">Удалить</a>
            </div>
        {% empty %}
            <div class="empty-cart">
                <h3>На данный момент в корзине нет товаров</h3>
                <a href="{% url 'shop:products' %}" class="btn btn-success">К покупкам</a>
            </div>
        {% endfor %}

        {% if products %}
            <div class="cart-summary">
                <h4>Итоговая цена: {{ final_price }} руб.</h4>
                <a href="{% url 'shop:ordered' %}" class="btn btn-primary">Оформить заказ</a>
            </div>
        {% endif %}
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/cart.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/category.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}{{ category.title }}{% endblock %}

{% block page_header %}
    <h1>{{ category.title }}</h1>
    <p>{{ category.description }}</p>  <!-- Полное описание категории -->
{% endblock %}

{% block content %}
    <div class="products-grid">
        {% for product in products %}
            <div class="product-item" id="product-{{product.id}}">
                <div class="product-inner">  <!-- Добавлена обертка -->
                    <a href="{% url 'shop:product' category.category_slug product.product_slug %}">
                        {% with product.productphoto_set.first as first_photo %}
                            {% if first_photo %}
                                <img src="{{ first_photo.photo.url }}" alt="{{ product.title }}" class="product-image">
                            {% else %}
                                <img src="{% static 'shop/images/placeholder.jpg' %}" alt="Placeholder" class="product-image">
                            {% endif %}
                        {% endwith %}
                        <h3>{{ product.title }}</h3>
                    </a>
                    <div class="product-description" id="description-{{product.id}}">
                        <p>{{ product.description|truncatechars:100 }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p class="text-center">В категории "{{ category.title }}" на данный момент нет товаров.</p>
        {% endfor %}
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/product_styles.css' %}">
    <script src="{% static 'shop/js/category.js' %}"></script>
{% endblock %}

KabanShop/shop/templates/shop/fill_profile.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Необходимо заполнить профиль{% endblock %}

{% block page_header %}
    <h1>Ваш профиль заполнен не полностью</h1>
{% endblock %}

{% block content %}
    <div class="fill-profile-container">
        <h3>Нам не удалось оформить заказ, поскольку ваш профиль заполнен не полностью. Пожалуйста, внесите изменения в профиль и повторите попытку</h3>
        <a href="{% url 'users:edit_profile' %}" class="btn btn-primary btn-edit-profile">Перейти к редактированию профиля</a>
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/fill_profile_styles.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block page_header %}
    <h1>Главная</h1>
{% endblock %}

{% block content %}
    <div class="kaban-hero">  <!-- Добавлен класс kaban-hero -->
        <h2>
            Самые разные товары высочайшего качества с быстрой доставкой только в KabanShop.<br>
            Поторопись оформить заказ!
        </h2><br>

        <a href="{% url 'shop:products' %}" class="btn btn-success">  <!-- Убраны inline-стили -->
            <img src="{% static 'shop/images/logo/logo.jpg' %}" alt="kaban" width="200px" height="200px">
            <strong>Оформить заказ</strong>
        </a>
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/index.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/order.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Добавить товар в корзину{% endblock %}

{% block page_header %}
    <h1>Добавить в корзину: <a href="{% url 'shop:product' category.category_slug product.product_slug %}">
        {{product}}</a></h1>
{% endblock %}

{% block content %}
    <form action="{% url 'shop:order' category.category_slug product.product_slug %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" button_class="btn btn-primary btn-lg" content="В корзину" %}
        <input type="hidden" name="next">
    </form>
{% endblock %}

KabanShop/shop/templates/shop/order_error.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Не удалось добавить товар{% endblock %}

{% block page_header %}
    <h1>Не удалось добавить товар в корзину</h1>
{% endblock %}

{% block content %}
    <div class="order-error-container">
        <h3>К сожалению, нам не удалось добавить товар в корзину, поскольку сейчас магазин не располагает таким количеством единиц товара.<br>Приносим свои извинения!</h3>
        <div class="buttons-container">
            <a href="{% url 'shop:index' %}" class="btn btn-primary">На главную</a>
            <a href="{% url 'shop:product' category.category_slug product.product_slug %}" class="btn btn-danger">Вернуться к карточке товара</a>
            <a href="{% url 'shop:order' category.category_slug product.product_slug %}" class="btn btn-success">Попробовать снова</a>
        </div>
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/order_error_styles.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/ordered.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Заказ оформлен{% endblock %}

{% block page_header %}
    <h1>Заказ оформлен</h1>
{% endblock %}

{% block content %}
    <div class="ordered-container">
        <h2 class="order-success-message">Спасибо за заказ! Ожидайте.</h2>
        <a href="{% url 'shop:index' %}" class="btn btn-success btn-go-home">
            <strong>На главную</strong>
            <img src="{% static 'shop/images/cart/img_1.png' %}" alt="kaban">
        </a>
    </div>
    <link rel="stylesheet" href="{% static 'shop/css/ordered_styles.css' %}">
{% endblock %}

KabanShop/shop/templates/shop/product.html
{% extends 'shop/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}{{ product.title }}{% endblock %}

{% block page_header %}
    <h1><a href="{% url 'shop:category' category.category_slug %}">{{ category.title }}</a></h1>
{% endblock %}

{% block content %}
    <div class="product-details">
        <h2>{{ product.title }}</h2>
        <p class="price">{{ product.price }} руб.</p>
        <p class="availability">{% if product.availability %}В наличии{% else %}Нет в наличии{% endif %}</p>
        <p class="description">{{ product.description|linebreaks }}</p>
        <a href="{% url 'shop:order' category.category_slug product.product_slug %}" class="btn btn-lg btn-success">В корзину</a>
    </div>

    {% if product_photo %}
        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
                {% for photo in product_photo %}
                    <div class="swiper-slide">
                        <img src="{{ photo.photo.url }}" alt="{{ photo.product.title }}_photo">
                    </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    {% endif %}


    <link rel="stylesheet" href="{% static 'slider/css/swiper-bundle.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'shop/css/product_styles.css' %}">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="{% static 'slider/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'shop/js/product.js' %}"></script>
{% endblock %}

KabanShop/shop/templates/shop/shop.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}Каталог товаров{% endblock %}

{% block page_header %}
    <h1>Каталог товаров</h1>
{% endblock %}

{% block content %}
    <div class="categories-list">
        {% for category in categories %}
            <div class="category-item" id="category-{{category.id}}">
                <a href="{% url 'shop:category' category.category_slug %}">
                    {% if category.preview %}
                        <img src="{{ category.preview.url }}" alt="{{ category.title }}" class="category-image">
                    {% else %}
                        <img src="{% static 'shop/images/placeholder.jpg' %}" alt="Placeholder" class="category-image">
                    {% endif %}
                    <h3>{{ category.title }}</h3>
                </a>
                <div class="category-description" id="description-{{category.id}}">
                    <p>{{ category.description|truncatechars:50 }}</p>
                </div>
            </div>
        {% empty %}
            <p class="text-center">На данный момент нет ни одной категории</p>
        {% endfor %}
    </div>

    <link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">
    <script src="{% static 'shop/js/shop.js' %}"></script>
{% endblock %}